// Generated by npm run build:dashboard. Edit dashboard-src/motion*.mjs instead.
/*! Bundled Motion / Framer Motion and motion-dom / motion-utils licenses:
The MIT License (MIT)

Copyright (c) 2024 [Motion](https://motion.dev) B.V.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

The MIT License (MIT)

Copyright (c) 2018 Framer B.V.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/
"use strict";
(() => {
  var P = () => {};
  var j = {};
  function z(t) {
    let e;
    return () => (e === void 0 && (e = t()), e);
  }
  var q = (t) => t;
  var V = (t) => t * 1e3,
    D = (t) => t / 1e3;
  var $ = (t) => Array.isArray(t) && typeof t[0] == "number";
  var A = { delta: 0, timestamp: 0, isProcessing: !1 };
  var L;
  function Ne() {
    L = void 0;
  }
  var H = {
    now: () => (
      L === void 0 &&
        H.set(
          A.isProcessing || j.useManualTiming ? A.timestamp : performance.now(),
        ),
      L
    ),
    set: (t) => {
      ((L = t), queueMicrotask(Ne));
    },
  };
  var ce = (t, e, o = 10) => {
    let i = "",
      a = Math.max(Math.round(e / o), 2);
    for (let u = 0; u < a; u++)
      i += Math.round(t(u / (a - 1)) * 1e4) / 1e4 + ", ";
    return `linear(${i.substring(0, i.length - 2)})`;
  };
  var we = (t) => t !== null;
  function de(t, { repeat: e, repeatType: o = "loop" }, i, a = 1) {
    let u = t.filter(we),
      x = a < 0 || (e && o !== "loop" && e % 2 === 1) ? 0 : u.length - 1;
    return !x || i === void 0 ? u[x] : i;
  }
  function ke(t, e) {
    return {
      kind: t,
      animation: e,
      timestamp: H.now(),
      frameTimestamp: A.timestamp,
      frameIsProcessing: A.isProcessing,
    };
  }
  function xe(t, e, o) {
    let i = globalThis.__MOTION_INSPECT__;
    if (i)
      try {
        i({ ...ke("animation-start", t), options: o ? { ...e, ...o } : e });
      } catch {}
  }
  var I = class {
    constructor() {
      this.isResolved = !1;
    }
    get finished() {
      return (
        this._finished ||
          (this._finished = this.isResolved
            ? Promise.resolve()
            : new Promise((e) => {
                this._resolve = e;
              })),
        this._finished
      );
    }
    updateFinished() {
      ((this._finished = this._resolve = void 0), (this.isResolved = !1));
    }
    notifyFinished() {
      ((this.isResolved = !0), this._resolve?.());
    }
    then(e, o) {
      return this.finished.then(e, o);
    }
  };
  function Y(t) {
    for (let e = 1; e < t.length; e++) t[e] ?? (t[e] = t[e - 1]);
  }
  var F = (t) => t.startsWith("--");
  function he(t, e, o) {
    F(e) ? t.style.setProperty(e, o) : (t.style[e] = o);
  }
  var ge = {};
  function R(t, e) {
    let o = z(t);
    return () => ge[e] ?? o();
  }
  var ye = R(() => window.ScrollTimeline !== void 0, "scrollTimeline");
  var N = R(() => {
    try {
      document
        .createElement("div")
        .animate({ opacity: 0 }, { easing: "linear(0, 1)" });
    } catch {
      return !1;
    }
    return !0;
  }, "linearEasing");
  var E = ([t, e, o, i]) => `cubic-bezier(${t}, ${e}, ${o}, ${i})`;
  var X = {
    linear: "linear",
    ease: "ease",
    easeIn: "ease-in",
    easeOut: "ease-out",
    easeInOut: "ease-in-out",
    circIn: E([0, 0.65, 0.55, 1]),
    circOut: E([0.55, 0, 1, 0.45]),
    backIn: E([0.31, 0.01, 0.66, -0.59]),
    backOut: E([0.33, 1.53, 0.69, 0.99]),
  };
  function U(t, e) {
    if (t)
      return typeof t == "function"
        ? N()
          ? ce(t, e)
          : "ease-out"
        : $(t)
          ? E(t)
          : Array.isArray(t)
            ? t.map((o) => U(o, e) || X.easeOut)
            : X[t];
  }
  function Se(
    t,
    e,
    o,
    {
      delay: i = 0,
      duration: a = 300,
      repeat: u = 0,
      repeatType: d = "loop",
      ease: x = "easeOut",
      times: l,
    } = {},
    s = void 0,
  ) {
    let p = { [e]: o };
    l && (p.offset = l);
    let c = U(x, a);
    Array.isArray(c) && (p.easing = c);
    let f = {
      delay: i,
      duration: a,
      easing: Array.isArray(c) ? "linear" : c,
      fill: "both",
      iterations: u + 1,
      direction: d === "reverse" ? "alternate" : "normal",
    };
    return (s && (f.pseudoElement = s), t.animate(p, f));
  }
  function Te(t) {
    return typeof t == "function" && "applyToOptions" in t;
  }
  function ve({ type: t, ...e }) {
    return Te(t) && N()
      ? t.applyToOptions(e)
      : (e.duration ?? (e.duration = 300), e.ease ?? (e.ease = "easeOut"), e);
  }
  var B = class extends I {
    constructor(e) {
      if (
        (super(),
        (this.finishedTime = null),
        (this.isStopped = !1),
        (this.manualStartTime = null),
        !e)
      )
        return;
      let {
        element: o,
        name: i,
        keyframes: a,
        pseudoElement: u,
        allowFlatten: d = !1,
        finalKeyframe: x,
        onComplete: l,
      } = e;
      ((this.isPseudoElement = !!u),
        (this.allowFlatten = d),
        (this.options = e),
        P(
          typeof e.type != "string",
          `Mini animate() doesn't support "type" as a string.`,
          "mini-spring",
        ));
      let s = ve(e);
      ((this.animation = Se(o, i, a, s, u)),
        s.autoplay === !1 && this.animation.pause(),
        (this.animation.onfinish = () => {
          if (((this.finishedTime = this.time), !u)) {
            let p = de(a, this.options, x, this.speed);
            (this.updateMotionValue && this.updateMotionValue(p),
              he(o, i, p),
              this.animation.cancel());
          }
          (l?.(), this.notifyFinished());
        }),
        xe(this, e, s));
    }
    play() {
      this.isStopped ||
        ((this.manualStartTime = null),
        this.animation.play(),
        this.state === "finished" && this.updateFinished());
    }
    pause() {
      this.animation.pause();
    }
    complete() {
      this.animation.finish?.();
    }
    cancel() {
      try {
        this.animation.cancel();
      } catch {}
    }
    stop() {
      if (this.isStopped) return;
      this.isStopped = !0;
      let { state: e } = this;
      e === "idle" ||
        e === "finished" ||
        (this.updateMotionValue
          ? this.updateMotionValue()
          : this.commitStyles(),
        this.isPseudoElement || this.cancel());
    }
    commitStyles() {
      let e = this.options?.element;
      !this.isPseudoElement &&
        e?.isConnected &&
        this.animation.commitStyles?.();
    }
    get duration() {
      let e = this.animation.effect?.getComputedTiming?.().duration || 0;
      return D(Number(e));
    }
    get iterationDuration() {
      let { delay: e = 0 } = this.options || {};
      return this.duration + D(e);
    }
    get time() {
      return D(Number(this.animation.currentTime) || 0);
    }
    set time(e) {
      let o = this.finishedTime !== null;
      ((this.manualStartTime = null),
        (this.finishedTime = null),
        (this.animation.currentTime = V(e)),
        o && this.animation.pause());
    }
    get speed() {
      return this.animation.playbackRate;
    }
    set speed(e) {
      (e < 0 && (this.finishedTime = null), (this.animation.playbackRate = e));
    }
    get state() {
      return this.finishedTime !== null ? "finished" : this.animation.playState;
    }
    get startTime() {
      return this.manualStartTime ?? Number(this.animation.startTime);
    }
    set startTime(e) {
      this.manualStartTime = this.animation.startTime = e;
    }
    attachTimeline({ timeline: e, onAttach: o, observe: i }) {
      return (
        this.allowFlatten &&
          this.animation.effect?.updateTiming({ easing: "linear" }),
        (this.animation.onfinish = null),
        e && ye()
          ? ((this.animation.timeline = e), o?.(this.animation), q)
          : i(this)
      );
    }
  };
  var w = class {
    constructor(e) {
      ((this.stop = () => this.runAll("stop")),
        (this.animations = e.filter(Boolean)));
    }
    get finished() {
      return Promise.all(this.animations.map((e) => e.finished));
    }
    getAll(e) {
      return this.animations[0][e];
    }
    setAll(e, o) {
      for (let i = 0; i < this.animations.length; i++)
        this.animations[i][e] = o;
    }
    attachTimeline(e) {
      let o = this.animations.map((i) => i.attachTimeline(e));
      return () => {
        o.forEach((i, a) => {
          (i && i(), this.animations[a].stop());
        });
      };
    }
    get time() {
      return this.getAll("time");
    }
    set time(e) {
      this.setAll("time", e);
    }
    get speed() {
      return this.getAll("speed");
    }
    set speed(e) {
      this.setAll("speed", e);
    }
    get state() {
      return this.getAll("state");
    }
    get startTime() {
      return this.getAll("startTime");
    }
    get duration() {
      return be(this.animations, "duration");
    }
    get iterationDuration() {
      return be(this.animations, "iterationDuration");
    }
    runAll(e) {
      this.animations.forEach((o) => o[e]());
    }
    play() {
      this.runAll("play");
    }
    pause() {
      this.runAll("pause");
    }
    cancel() {
      this.runAll("cancel");
    }
    complete() {
      this.runAll("complete");
    }
  };
  function be(t, e) {
    let o = 0;
    for (let i = 0; i < t.length; i++) {
      let a = t[i][e];
      a !== null && a > o && (o = a);
    }
    return o;
  }
  var C = class extends w {
    then(e, o) {
      return this.finished.finally(e).then(() => {});
    }
  };
  var Ee = new WeakMap(),
    Z = (t, e = "") => `${t}:${e}`;
  function J(t) {
    let e = Ee.get(t);
    return (e || ((e = new Map()), Ee.set(t, e)), e);
  }
  function Ve(t, e) {
    if (t?.inherit && e) {
      let { inherit: o, ...i } = t;
      return { ...e, ...i };
    }
    return t;
  }
  function Q(t, e) {
    let o = t?.[e] ?? t?.default ?? t;
    return o !== t ? Ve(o, t) : o;
  }
  var Ae = [
    "borderTopLeftRadius",
    "borderTopRightRadius",
    "borderBottomRightRadius",
    "borderBottomLeftRadius",
  ];
  var Me = new Set([
    "borderWidth",
    "borderTopWidth",
    "borderRightWidth",
    "borderBottomWidth",
    "borderLeftWidth",
    "borderRadius",
    ...Ae,
    "width",
    "maxWidth",
    "height",
    "maxHeight",
    "top",
    "right",
    "bottom",
    "left",
    "inset",
    "insetBlock",
    "insetBlockStart",
    "insetBlockEnd",
    "insetInline",
    "insetInlineStart",
    "insetInlineEnd",
    "padding",
    "paddingTop",
    "paddingRight",
    "paddingBottom",
    "paddingLeft",
    "paddingBlock",
    "paddingBlockStart",
    "paddingBlockEnd",
    "paddingInline",
    "paddingInlineStart",
    "paddingInlineEnd",
    "margin",
    "marginTop",
    "marginRight",
    "marginBottom",
    "marginLeft",
    "marginBlock",
    "marginBlockStart",
    "marginBlockEnd",
    "marginInline",
    "marginInlineStart",
    "marginInlineEnd",
    "fontSize",
    "backgroundPositionX",
    "backgroundPositionY",
  ]);
  function ee(t, e) {
    for (let o = 0; o < t.length; o++)
      typeof t[o] == "number" && Me.has(e) && (t[o] = t[o] + "px");
  }
  function te(t, e, o) {
    if (t == null) return [];
    if (t instanceof EventTarget) return [t];
    if (typeof t == "string") {
      let i = document;
      e && (i = e.current);
      let a = o?.[t] ?? i.querySelectorAll(t);
      return a ? Array.from(a) : [];
    }
    return Array.from(t).filter((i) => i != null);
  }
  function k(t, e) {
    let o = window.getComputedStyle(t);
    return F(e) ? o.getPropertyValue(e) : o[e];
  }
  function Pe(t, e, o, i) {
    if (t == null) return [];
    let a = te(t, i),
      u = a.length;
    P(!!u, "No valid elements provided.", "no-valid-elements");
    let d = [];
    for (let l = 0; l < u; l++) {
      let s = a[l],
        p = { ...o };
      typeof p.delay == "function" && (p.delay = p.delay(l, u));
      for (let c in e) {
        let f = e[c];
        Array.isArray(f) || (f = [f]);
        let h = { ...Q(p, c) };
        (h.duration && (h.duration = V(h.duration)),
          h.delay && (h.delay = V(h.delay)));
        let v = J(s),
          y = Z(c, h.pseudoElement || ""),
          M = v.get(y);
        (M && M.stop(),
          d.push({
            map: v,
            key: y,
            unresolvedKeyframes: f,
            options: {
              ...h,
              element: s,
              name: c,
              allowFlatten: !p.type && !p.ease,
            },
          }));
      }
    }
    for (let l = 0; l < d.length; l++) {
      let { unresolvedKeyframes: s, options: p } = d[l],
        { element: c, name: f, pseudoElement: h } = p;
      (!h && s[0] === null && (s[0] = k(c, f)),
        Y(s),
        ee(s, f),
        !h && s.length < 2 && s.unshift(k(c, f)),
        (p.keyframes = s));
    }
    let x = [];
    for (let l = 0; l < d.length; l++) {
      let { map: s, key: p, options: c } = d[l],
        f = new B(c);
      (s.set(p, f), f.finished.finally(() => s.delete(p)), x.push(f));
    }
    return x;
  }
  var Ge = (t) => {
      function e(o, i, a) {
        return new C(Pe(o, i, a, t));
      }
      return e;
    },
    re = Ge();
  var De = 'dialog, [role="dialog"], [data-motion-reveal]',
    We = '[hidden], [inert], [aria-hidden="true"]',
    Ke = 'input, textarea, select, [contenteditable="true"]';
  function Be({ window: t, document: e, animate: o }) {
    let i = t.matchMedia("(prefers-reduced-motion: reduce)"),
      a = new Map(),
      u = new WeakSet(),
      d = new WeakSet(),
      x = new Set(),
      l = new Map(),
      s = new Set(),
      p = null,
      c = !1;
    function f(r) {
      if (
        !r?.isConnected ||
        r.closest(We) ||
        (r.tagName === "DIALOG" && !r.open) ||
        !r.getClientRects().length
      )
        return !1;
      let n = t.getComputedStyle(r);
      return n.visibility !== "hidden" && n.visibility !== "collapse";
    }
    function h(r) {
      let n = e.activeElement;
      return !!(n?.matches?.(Ke) && r.contains(n));
    }
    function v(r) {
      let n = a.get(r);
      n && (a.delete(r), n.control.cancel(), n.restore());
    }
    function y() {
      for (let r of s) t.cancelAnimationFrame(r);
      s.clear();
      for (let r of a.keys()) v(r);
    }
    function M(r, n, m) {
      (r.size >= 500 && !r.has(n) && r.delete(r.keys().next().value),
        r instanceof Map ? r.set(n, m) : r.add(n));
    }
    function G(r, n = "card", m = 0) {
      if (
        c ||
        i.matches ||
        e.visibilityState === "hidden" ||
        !f(r) ||
        (n !== "dialog" && h(r)) ||
        typeof r.animate != "function"
      )
        return !1;
      v(r);
      let g = t.getComputedStyle(r),
        S = Number.parseFloat(g.opacity);
      if (!Number.isFinite(S) || S <= 0) return !1;
      let b = g.transform || "none",
        Ie = n === "card" || n === "dialog",
        W = { opacity: String(S) },
        fe = { opacity: [S * 0.65, S] };
      Ie &&
        ((W.transform = b),
        (fe.transform = [
          `${b === "none" ? "" : `${b} `}translateY(${n === "dialog" ? 8 : 5}px)`,
          b,
        ]));
      let Fe = Object.fromEntries(
          Object.keys(W).map((T) => [
            T,
            [r.style.getPropertyValue(T), r.style.getPropertyPriority(T)],
          ]),
        ),
        O = () => {
          for (let [T, [ue, Re]] of Object.entries(Fe))
            r.style.getPropertyValue(T) === W[T] &&
              (ue ? r.style.setProperty(T, ue, Re) : r.style.removeProperty(T));
        },
        K;
      try {
        K = o(r, fe, {
          duration: n === "state" ? 0.14 : n === "dialog" ? 0.2 : 0.18,
          delay: Math.max(0, Math.min(Number(m) || 0, 0.12)),
          ease: [0.2, 0.65, 0.3, 1],
        });
      } catch {
        return (O(), !1);
      }
      let _ = { control: K, restore: O };
      return (
        a.set(r, _),
        Promise.resolve(K.finished).then(
          () => {
            a.get(r) === _ && (a.delete(r), O());
          },
          () => {
            a.get(r) === _ && (a.delete(r), O());
          },
        ),
        !0
      );
    }
    function oe(r, { key: n, kind: m = "card", delay: g = 0 } = {}) {
      return !f(r) ||
        u.has(r) ||
        (n && x.has(n)) ||
        (u.add(r), n && x.size >= 500)
        ? !1
        : (n && M(x, n), G(r, m, g));
    }
    function ie(r, { kind: n = "dialog" } = {}) {
      return !f(r) || d.has(r) ? !1 : (d.add(r), G(r, n));
    }
    function ne(r) {
      r && (d.delete(r), v(r));
    }
    function Oe(r, { key: n, value: m } = {}) {
      if (!n || c) return !1;
      let g = l.get(n),
        S = l.has(n);
      return (M(l, n, m), !S || g === m ? !1 : G(r, "state"));
    }
    function Le(r) {
      let n = t.requestAnimationFrame(() => {
        (s.delete(n), c || r());
      });
      s.add(n);
    }
    function ae(r) {
      let n = r.detail || {},
        m = new URL(n.path || t.location.href, t.location.href);
      m.searchParams.delete("run");
      let g = m.pathname + m.search + m.hash;
      g !== p &&
        ((p = g),
        y(),
        (u = new WeakSet()),
        x.clear(),
        l.clear(),
        Le(() => {
          let S = 0;
          for (let b of e.querySelectorAll("[data-page]"))
            f(b) && oe(b, { kind: "page", delay: Math.min(S++ * 0.025, 0.1) });
        }));
    }
    function se() {
      i.matches && y();
    }
    function me() {
      e.visibilityState === "hidden" && y();
    }
    let le = new t.MutationObserver((r) => {
      let n = new Set();
      for (let { target: m } of r) {
        m.matches?.(De) && n.add(m);
        for (let g of m.querySelectorAll?.(De) || []) n.add(g);
      }
      for (let m of n) f(m) ? ie(m) : ne(m);
      for (let m of a.keys()) f(m) || v(m);
    });
    (le.observe(e.body, {
      subtree: !0,
      attributes: !0,
      attributeFilter: ["open", "hidden", "aria-hidden", "inert"],
    }),
      t.addEventListener("dashboard:pagechange", ae),
      t.addEventListener("pagehide", y),
      e.addEventListener("visibilitychange", me),
      i.addEventListener("change", se));
    let pe = {
      enter: oe,
      reveal: ie,
      hide: ne,
      transition: Oe,
      get reducedMotion() {
        return i.matches;
      },
      destroy() {
        c ||
          ((c = !0),
          y(),
          le.disconnect(),
          x.clear(),
          l.clear(),
          (d = new WeakSet()),
          t.removeEventListener("dashboard:pagechange", ae),
          t.removeEventListener("pagehide", y),
          e.removeEventListener("visibilitychange", me),
          i.removeEventListener("change", se),
          t.dashboardMotion === pe && delete t.dashboardMotion);
      },
    };
    return pe;
  }
  function Ce() {
    (window.dashboardMotion?.destroy(),
      (window.dashboardMotion = Be({ window, document, animate: re })));
  }
  document.readyState === "loading"
    ? document.addEventListener("DOMContentLoaded", Ce, { once: !0 })
    : Ce();
})();
