"use strict";

(() => {
  const ranges = {
    "7d": "Last 7 days",
    "30d": "Last 30 days",
    all: "All time",
  };
  const categories = [
    ["inputTokens", "Input", "Not served from cache"],
    ["outputTokens", "Output", "Generated by the model"],
    ["cacheReadInputTokens", "Cache reads", "Reused context"],
    ["cacheCreationInputTokens", "Cache creation", "Context written to cache"],
  ];
  const node = (tag, className = "", text) => {
    const value = document.createElement(tag);
    value.className = className;
    if (text !== undefined) value.textContent = String(text);
    return value;
  };
  const number = (value) => new Intl.NumberFormat().format(value);
  const compact = (value) =>
    value >= 100000
      ? new Intl.NumberFormat(undefined, {
          notation: "compact",
          maximumFractionDigits: 1,
        }).format(value)
      : number(value);
  const count = (coverage, key) => Math.max(0, Number(coverage?.[key]) || 0);
  const measured = (coverage) =>
    count(coverage, "measuredRuns") + count(coverage, "measuredOperations");
  const unavailable = (coverage) =>
    count(coverage, "unavailableRuns") +
    count(coverage, "unavailableOperations");
  const hasReports = (coverage) =>
    measured(coverage) > 0 || count(coverage, "partialRecords") > 0;
  const known = (record) => hasReports(record?.coverage);
  const projectName = (project) => project || "Workspace planning";
  const identity = (row) =>
    JSON.stringify([row.project, row.projectInstanceId]);
  const dayLabel = (date) =>
    new Intl.DateTimeFormat(undefined, {
      month: "short",
      day: "numeric",
      timeZone: "UTC",
    }).format(new Date(`${date}T00:00:00Z`));
  function totalsLabel(row, key = "totalTokens") {
    if (!known(row)) return "—";
    if (key !== "totalTokens" && !count(row.coverage?.fields, key)) return "—";
    return `${count(row.coverage, "partialRecords") ? "≥ " : ""}${number(row.totals[key])}`;
  }
  function button(label, action) {
    const result = node("button", "small-button", label);
    result.type = "button";
    result.addEventListener("click", action);
    return result;
  }
  function filterPath(filters) {
    const query = new URLSearchParams({ range: filters.range });
    if (filters.project) {
      query.set("project", filters.project);
      if (filters.instance) query.set("instance", filters.instance);
    }
    return `/usage?${query}`;
  }
  function filtersFrom(path) {
    const url = new URL(path, window.location.origin);
    return {
      range: Object.hasOwn(ranges, url.searchParams.get("range"))
        ? url.searchParams.get("range")
        : "30d",
      project: url.searchParams.get("project") || "",
      instance: url.searchParams.get("instance") || "",
    };
  }
  // Preserve missing/partial coverage when coalescing a long all-time timeline.
  function buckets(days, from, to) {
    const first = from?.slice(0, 10) || days[0]?.date;
    if (!first) return [];
    const start = Date.parse(`${first}T00:00:00Z`);
    const last = Date.parse(`${to.slice(0, 10)}T00:00:00Z`);
    const dayCount = Math.max(1, Math.round((last - start) / 86400000) + 1);
    const width = Math.max(1, Math.ceil(dayCount / 60));
    const date = (offset) =>
      new Date(start + offset * 86400000).toISOString().slice(0, 10);
    const result = [];
    for (let offset = 0; offset < dayCount; offset += width) {
      result.push({
        date: date(offset),
        end: date(Math.min(dayCount - 1, offset + width - 1)),
        totals: { totalTokens: 0 },
        coverage: {},
      });
    }
    for (const day of days) {
      const offset = Math.round(
        (Date.parse(`${day.date}T00:00:00Z`) - start) / 86400000,
      );
      const value = result[Math.floor(offset / width)];
      if (!value) continue;
      value.totals.totalTokens += day.totals.totalTokens;
      for (const key of [
        "measuredRuns",
        "unavailableRuns",
        "measuredOperations",
        "unavailableOperations",
        "partialRecords",
      ])
        value.coverage[key] =
          (value.coverage[key] || 0) + count(day.coverage, key);
    }
    return result;
  }
  function chart(days, from, to) {
    const card = node("section", "usage-card usage-trend");
    const heading = node("div", "usage-section-heading");
    heading.append(
      node("h2", "", "Over time"),
      node("span", "usage-meta", "UTC"),
    );
    card.append(heading);
    const values = buckets(days, from, to);
    if (!values.length) {
      card.append(
        node("p", "usage-muted", "A trend will appear as usage is recorded."),
      );
      return card;
    }
    const max = Math.max(0, ...values.map((day) => day.totals.totalTokens));
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("viewBox", "0 0 900 170");
    svg.setAttribute("preserveAspectRatio", "none");
    svg.setAttribute("aria-hidden", "true");
    svg.classList.add("usage-chart");
    const step = 900 / values.length;
    values.forEach((day, index) => {
      const rect = document.createElementNS(
        "http://www.w3.org/2000/svg",
        "rect",
      );
      const height = max ? (day.totals.totalTokens / max) * 145 : 0;
      rect.setAttribute("x", String(index * step + Math.min(3, step * 0.16)));
      rect.setAttribute(
        "width",
        String(Math.max(1, step - Math.min(6, step * 0.32))),
      );
      rect.setAttribute("y", String(160 - Math.max(height, 3)));
      rect.setAttribute("height", String(Math.max(height, 3)));
      rect.setAttribute("rx", "3");
      rect.setAttribute(
        "class",
        `usage-bar${!known(day) ? " usage-bar-unknown" : ""}`,
      );
      const title = document.createElementNS(
        "http://www.w3.org/2000/svg",
        "title",
      );
      title.textContent = `${day.date}${day.end !== day.date ? ` to ${day.end}` : ""}: ${known(day) ? `${totalsLabel(day)} recorded tokens` : unavailable(day.coverage) ? "Usage not reported" : "No recorded activity"}`;
      rect.append(title);
      svg.append(rect);
    });
    const scale = node("div", "usage-chart-scale");
    scale.append(
      node("span", "", max ? `${compact(max)} peak` : "No measured tokens yet"),
      node("span", "", "0"),
    );
    const graphic = node("div", "usage-chart-frame");
    graphic.append(scale, svg);
    const axis = node("div", "usage-chart-axis");
    axis.append(
      node("span", "", dayLabel(values[0].date)),
      node("span", "", dayLabel(values[values.length - 1].end)),
    );
    card.append(
      graphic,
      axis,
      node(
        "p",
        "usage-muted usage-chart-note",
        values.some(
          (day) =>
            unavailable(day.coverage) || count(day.coverage, "partialRecords"),
        )
          ? "Recorded tokens only. Missing reports can leave gaps or understate a day’s total."
          : `${values.some((day) => day.date !== day.end) ? "Grouped daily" : "Daily"} totals. Days without recorded activity are shown on the baseline.`,
      ),
    );
    // A real data table gives screen readers the same dates and values as the
    // graphic without forcing keyboard users through dozens of chart controls.
    const accessible = node("table");
    accessible.append(node("caption", "", "Recorded token trend"));
    const head = node("thead"),
      header = node("tr");
    for (const label of ["Date (UTC)", "Recorded tokens", "Reporting"])
      header.append(node("th", "", label));
    head.append(header);
    const body = node("tbody");
    for (const day of values) {
      const row = node("tr");
      row.append(
        node(
          "th",
          "",
          day.date === day.end ? day.date : `${day.date} to ${day.end}`,
        ),
        node("td", "", totalsLabel(day)),
        node(
          "td",
          "",
          `${measured(day.coverage)} reported; ${unavailable(day.coverage)} unavailable; ${count(day.coverage, "partialRecords")} partial`,
        ),
      );
      body.append(row);
    }
    accessible.append(head, body);
    const accessibleContainer = node("div", "sr-only");
    accessibleContainer.append(accessible);
    card.append(accessibleContainer);
    return card;
  }
  window.createWorkspaceUsage = (
    root,
    { api, pages, canRead = () => true },
  ) => {
    if (!root) return null;
    let filters = filtersFrom(window.location.href),
      serial = 0,
      controller;
    let catalog = [],
      catalogReady = false,
      catalogRequest;
    const title = node("div", "panel-heading usage-heading");
    const copy = node("div");
    const h1 = node("h1", "", "Usage");
    h1.id = "usage-title";
    copy.append(
      node("span", "eyebrow muted", "A CLEARER PICTURE"),
      h1,
      node("p", "", "See the tokens your crew uses, across every project."),
    );
    const refresh = button("Refresh", () => load(true));
    title.append(copy, refresh);
    const controls = node("div", "usage-controls");
    const periods = node("div", "usage-periods");
    periods.setAttribute("role", "group");
    periods.setAttribute("aria-label", "Usage period");
    const rangeButtons = new Map();
    for (const [key, label] of Object.entries(ranges)) {
      const item = button(label, () => navigate({ ...filters, range: key }));
      rangeButtons.set(key, item);
      periods.append(item);
    }
    const projectField = node("div", "usage-project-filter");
    const label = node("label", "", "Project");
    label.htmlFor = "usage-project";
    const projectSelect = node("select");
    projectSelect.id = "usage-project";
    projectSelect.addEventListener("change", () => {
      const selected = projectSelect.value
        ? JSON.parse(projectSelect.value)
        : ["", ""];
      navigate({ ...filters, project: selected[0], instance: selected[1] });
    });
    projectField.append(label, projectSelect);
    controls.append(periods, projectField);
    const status = node("p", "usage-status");
    status.setAttribute("role", "status");
    status.setAttribute("aria-live", "polite");
    const content = node("div", "usage-content");
    root.append(title, controls, status, content);
    function updateControls() {
      for (const [key, item] of rangeButtons)
        item.setAttribute("aria-pressed", String(key === filters.range));
      projectSelect.replaceChildren();
      const all = node("option", "", "All projects");
      all.value = "";
      projectSelect.append(all);
      const choices = new Map();
      const selectKey = (project, instance) =>
        JSON.stringify([project, instance]);
      for (const row of catalog) {
        const project = row.project || "_workspace",
          instance = row.project ? row.projectInstanceId || "legacy" : "";
        const duplicate =
          catalog.filter((other) => other.project === row.project).length > 1;
        choices.set(
          selectKey(project, instance),
          `${projectName(row.project)}${duplicate ? ` · ${row.projectInstanceId ? row.projectInstanceId.slice(0, 8) : "legacy"}` : ""}`,
        );
        if (duplicate)
          choices.set(
            selectKey(project, ""),
            `${projectName(row.project)} · All history`,
          );
      }
      const selected = filters.project
        ? selectKey(filters.project, filters.instance)
        : "";
      if (selected && !choices.has(selected))
        choices.set(
          selected,
          `${projectName(filters.project === "_workspace" ? null : filters.project)}${!filters.instance && filters.project !== "_workspace" ? " · All history" : ""}`,
        );
      for (const [key, label] of [...choices].sort((a, b) =>
        a[1].localeCompare(b[1]),
      )) {
        const item = node("option", "", label);
        item.value = key;
        projectSelect.append(item);
      }
      projectSelect.value = selected;
    }
    function navigate(next) {
      const path = filterPath(next);
      if (!pages?.navigate(path, { focus: false, scroll: false })) {
        filters = next;
        load();
      }
    }
    function coverage(row) {
      const reported = measured(row),
        missing = unavailable(row),
        partial = count(row, "partialRecords");
      return `${number(reported)} reported${missing ? ` · ${number(missing)} unavailable` : ""}${partial ? ` · ${number(partial)} partial` : ""}`;
    }
    function render(data) {
      const metrics = node("div", "usage-metrics");
      const total = node("section", "usage-total");
      const value = known(data) ? compact(data.totals.totalTokens) : "—";
      total.append(
        node("span", "usage-kicker", "Recorded tokens"),
        node(
          "strong",
          "usage-total-value",
          `${known(data) && count(data.coverage, "partialRecords") ? "≥ " : ""}${value}`,
        ),
        node(
          "p",
          "usage-exact",
          known(data)
            ? `${totalsLabel(data)} tokens reported`
            : "No token totals reported yet",
        ),
        node(
          "p",
          "usage-total-scope",
          `${filters.project ? projectName(filters.project === "_workspace" ? null : filters.project) : "All projects"} · ${ranges[filters.range]}`,
        ),
      );
      metrics.append(total);
      const breakdown = node("div", "usage-breakdown");
      for (const [key, name, hint] of categories) {
        const card = node("section", "usage-card usage-token-card");
        card.append(
          node("h2", "", name),
          node("strong", "", totalsLabel(data, key)),
          node("p", "", hint),
        );
        breakdown.append(card);
      }
      metrics.append(breakdown);
      const measurement = node(
        "p",
        "usage-muted usage-definition",
        "Token totals include input, output, cache reads, and cache creation. They are not a cost estimate or your provider’s account balance. Usage updates after runs and AI setup actions finish; refresh for the latest reports.",
      );
      const reporting = node("section", "usage-card usage-coverage");
      const reported = measured(data.coverage),
        missing = unavailable(data.coverage),
        partial = count(data.coverage, "partialRecords");
      const reportingTitle =
        reported || missing || partial
          ? "Reporting coverage"
          : "Your first tokens will appear here";
      reporting.append(node("h2", "", reportingTitle));
      reporting.append(
        node(
          "p",
          "usage-coverage-summary",
          `${number(count(data.coverage, "measuredRuns"))} of ${number(count(data.coverage, "measuredRuns") + count(data.coverage, "unavailableRuns"))} runs reported · ${number(count(data.coverage, "measuredOperations"))} of ${number(count(data.coverage, "measuredOperations") + count(data.coverage, "unavailableOperations"))} AI operations reported`,
        ),
      );
      reporting.append(
        node(
          "p",
          "usage-muted",
          missing || partial
            ? "Missing reports are unknown, not zero. Older work may have no token data; interrupted or partial reports may omit tokens. The totals above include only what was recorded."
            : reported
              ? "Every recorded run and AI operation in this selection has a usage report. New or unfinished work appears when its usage is saved."
              : "Use a gremlin or an AI setup action to start recording usage. Historical token counts cannot be reconstructed from runs that did not report them.",
        ),
      );
      if (partial)
        reporting.append(
          node(
            "p",
            "usage-muted",
            `${number(partial)} partial ${partial === 1 ? "report is" : "reports are"} included. ≥ marks a lower bound; more tokens may have been used.`,
          ),
        );
      for (const warning of data.warnings || [])
        reporting.append(node("p", "usage-warning", warning));
      const tableCard = node("section", "usage-card usage-projects");
      const tableHeading = node("div", "usage-section-heading");
      const projectCount = data.projects.filter((row) => row.project).length;
      tableHeading.append(
        node("h2", "", "By project"),
        node(
          "span",
          "usage-meta",
          `${projectCount} ${projectCount === 1 ? "project" : "projects"}${data.projects.some((row) => !row.project) ? " + workspace planning" : ""}`,
        ),
      );
      tableCard.append(tableHeading);
      if (!data.projects.length)
        tableCard.append(
          node(
            "p",
            "usage-muted",
            "No recorded activity for this selection. Try another period or project.",
          ),
        );
      else {
        const table = node("table", "usage-table");
        table.append(
          node(
            "caption",
            "sr-only",
            "Token usage and report coverage by project",
          ),
        );
        const head = node("thead"),
          header = node("tr");
        const labels = [
          "Project",
          "Recorded tokens",
          "Input",
          "Output",
          "Cache reads",
          "Cache creation",
          "Reports",
        ];
        for (const label of labels) {
          const th = node("th", "", label);
          th.scope = "col";
          header.append(th);
        }
        head.append(header);
        const body = node("tbody");
        for (const row of [...data.projects].sort(
          (a, b) =>
            b.totals.totalTokens - a.totals.totalTokens ||
            projectName(a.project).localeCompare(projectName(b.project)),
        )) {
          const tr = node("tr");
          const name = node("th");
          name.scope = "row";
          const link = node(
            "a",
            "usage-project-link",
            projectName(row.project),
          );
          link.href = filterPath({
            ...filters,
            project: row.project || "_workspace",
            instance: row.project ? row.projectInstanceId || "legacy" : "",
          });
          name.append(link);
          if (
            data.projects.filter((other) => other.project === row.project)
              .length > 1
          )
            name.append(
              node(
                "small",
                "usage-muted",
                row.projectInstanceId
                  ? `Project ${row.projectInstanceId.slice(0, 8)}`
                  : "Legacy project",
              ),
            );
          tr.append(name);
          const values = [
            totalsLabel(row),
            ...categories.map(([key]) => totalsLabel(row, key)),
            coverage(row.coverage),
          ];
          values.forEach((value, index) => {
            const td = node("td", index === 5 ? "usage-report-cell" : "");
            const mobile = node("span", "usage-cell-label", labels[index + 1]);
            mobile.setAttribute("aria-hidden", "true");
            td.append(mobile, node("span", "usage-cell-value", value));
            tr.append(td);
          });
          body.append(tr);
        }
        table.append(head, body);
        tableCard.append(table);
      }
      content.replaceChildren(
        metrics,
        measurement,
        chart(data.daily, data.from, data.to),
        tableCard,
        reporting,
      );
    }
    async function catalogFor() {
      if (catalogReady) return;
      if (!catalogRequest)
        catalogRequest = api("/api/usage?range=all")
          .then((data) => {
            catalog = data.projects;
            catalogReady = true;
          })
          .finally(() => {
            catalogRequest = null;
          });
      await catalogRequest;
    }
    async function load(force = false) {
      const request = ++serial;
      controller?.abort();
      controller = new AbortController();
      updateControls();
      if (!canRead()) {
        content.replaceChildren();
        status.textContent =
          "Open your private dashboard session to view token usage.";
        refresh.disabled = true;
        content.setAttribute("aria-busy", "false");
        return;
      }
      if (force) catalogReady = false;
      refresh.disabled = true;
      content.setAttribute("aria-busy", "true");
      status.textContent = "Loading token usage…";
      content.replaceChildren(
        node("div", "usage-loading", "Gathering your recorded usage…"),
      );
      try {
        const query = filterPath(filters).replace("/usage", "/api/usage");
        const [data, list] = await Promise.allSettled([
          api(query, undefined, "GET", 20000, controller.signal),
          catalogFor(),
        ]);
        if (request !== serial) return;
        if (data.status === "rejected") throw data.reason;
        if (!catalogReady) {
          const rows = new Map(catalog.map((row) => [identity(row), row]));
          for (const row of data.value.projects) rows.set(identity(row), row);
          catalog = [...rows.values()];
        }
        updateControls();
        render(data.value);
        status.textContent =
          list.status === "rejected"
            ? "Usage loaded. Some project filter options could not load; refresh to retry."
            : `${ranges[filters.range]} · Dates are UTC · ${coverage(data.value.coverage)}`;
      } catch (error) {
        if (request !== serial) return;
        const empty = node("div", "usage-card usage-error");
        empty.append(
          node("h2", "", "Usage couldn’t load"),
          node(
            "p",
            "usage-muted",
            error.message || "Check your connection and try again.",
          ),
          button("Try again", () => load(true)),
        );
        content.replaceChildren(empty);
        status.textContent =
          "Token usage is unavailable. Your work is unchanged.";
      } finally {
        if (request === serial) {
          content.setAttribute("aria-busy", "false");
          refresh.disabled = false;
        }
      }
    }
    const onPage = (event) => {
      if (event.detail.page !== "usage") {
        serial++;
        controller?.abort();
        return;
      }
      filters = filtersFrom(event.detail.path);
      load();
    };
    window.addEventListener("dashboard:pagechange", onPage);
    updateControls();
    if (pages?.current === "usage") load();
    return {
      refresh: () => load(true),
      destroy() {
        serial++;
        controller?.abort();
        window.removeEventListener("dashboard:pagechange", onPage);
      },
    };
  };
})();
